#!/usr/bin/env node
'use strict';

const argv = require('../../lib/args')();
const getMetadata = require('../metadata');
const CLI = require('../../lib/cli');
const config = require('../../lib/config').getMergedConfig();

const logStream = process.stdout.isTTY ? process.stdout : process.stderr;
const cli = new CLI(logStream);

getMetadata(Object.assign({}, config, argv), cli).catch((err) => {
  if (cli.spinner.enabled) {
    cli.spinner.fail();
  }
  cli.error(err);
  process.exit(-1);
});
