query PR($prid: Int!, $owner: String!, $repo: String!) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $prid) {
      createdAt,
      authorAssociation,
      author {
        login
      },
      url,
      bodyHTML,
      bodyText,
      labels(first: 100) {
        nodes {
          name
        }
      },
      title,
      baseRefName,
      headRefName
    }
  }
}
