query PR($prid: Int!, $owner: String!, $repo: String!) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $prid) {
      url,
      bodyHTML
      labels(first: 100) {
        nodes {
          name
        }
      }
    }
  }
}
