query Commits($prid: Int!, $owner: String!, $repo: String!, $after: String) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $prid) {
      commits(first: 100, after: $after) {
        totalCount
        nodes {
          commit {
            committedDate
            author {
              email
              name
            }
            committer {
              email
              name
            }
            oid
            message
            authoredByCommitter
          }
        }
      }
    }
  }
}
