'use strict';

module.exports = {
  FIRST_TIME_CONTRIBUTOR: 'FIRST_TIME_CONTRIBUTOR',
  NONE: 'NONE',
  OWNER: 'OWNER',  // TSC
  FIRST_TIMER: 'FIRST_TIMER',  // New to Github
  COLLABORATOR: 'COLLABORATOR'
};
