query PR($owner: String!, $repo: String!) {
  repository(owner: $owner, name: $repo) {
    pullRequests(states: OPEN, first: 2, orderBy: {field: CREATED_AT, direction: DESC}) {
      nodes {
        number
        headRefOid
        author {
          login
        }

        files(first: 2) {
          nodes {
            path
          }
        }
      }
    }
  }
}
