query SearchIssueByUser($queryString: String!, $mustBeAuthor: Boolean!, $after: String) {
  search(query: $queryString, type: ISSUE, first: 100, after: $after) {
    issueCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      ... on PullRequest {
        url
        publishedAt
        author {
          login
        }
        title
        reviews(last: 100) @skip(if: $mustBeAuthor) {
          nodes {
            publishedAt
            author {
              login
            }
          }
        }
        labels(first: 100) {
          nodes {
            name
          }
        }
        comments(last: 100) @skip(if: $mustBeAuthor) {
          nodes {
            publishedAt
            author {
              login
            }
          }
        }
      }
      ... on Issue {
        publishedAt
        url
        author {
          login
        }
        title
        comments(last: 100) @skip(if: $mustBeAuthor) {
          nodes {
            publishedAt
            author {
              login
            }
          }
        }
      }
    }
  }
}
