import semver from 'semver';
import * as TOML from 'smol-toml';
import { promises as fs } from 'node:fs';
import path from 'node:path';

import { removeDirectory } from './util.js';
import { forceRunAsync } from '../run.js';

export default function updateCrates() {
  return {
    title: 'Update Rust crates',
    skip: (ctx) => ctx.newVersion.majorMinor < 139,
    task: (ctx, task) => {
      return task.newListr([
        enumerateTemporalDependencies(),
        removeExistingCrates(),
        buildManifest(),
        vendorCrates(),
        generateLockfile(),
        updateGYP(),
        commitChanges()
      ]);
    }
  };
}

const chromiumCratesDir = 'deps/v8/third_party/rust/chromium_crates_io';
const nodeCratesDir = 'deps/crates';

function enumerateTemporalDependencies() {
  return {
    title: 'Enumerate Temporal dependency tree',
    task: async(ctx) => {
      const tree = await forceRunAsync(
        ctx.cargo,
        ['tree', '-Z', 'bindeps', '--package', 'temporal_capi', '--prefix', 'none'],
        {
          ignoreFailure: false,
          captureStdout: true,
          spawnArgs: { cwd: path.join(ctx.nodeDir, chromiumCratesDir) }
        }
      );
      const crates = new Set();
      for (const crate of tree.trimEnd().split('\n').sort()) {
        const [name, version] = crate.split(' ', 2);
        crates.add(`${name}@${version.substring(1)}`);
      }
      ctx.temporalCrates = crates;
    },
  };
}

function removeExistingCrates() {
  return {
    title: 'Remove existing crates',
    task: (ctx) => removeDirectory(path.join(ctx.nodeDir, nodeCratesDir, 'vendor'))
  };
}

function buildManifest() {
  return {
    title: 'Build new manifest',
    task: async(ctx) => {
      const sourceManifest = TOML.parse(
        await fs.readFile(path.join(ctx.nodeDir, chromiumCratesDir, 'Cargo.toml'), 'utf8')
      );

      const header =
      '# This manifest is generated by node-core-utils. Do not modify it directly.\n\n';
      const manifest = {
        package: {
          edition: sourceManifest.package.edition,
          name: 'node_crates',
          version: `${ctx.newVersion.major}.${ctx.newVersion.minor}.${ctx.newVersion.build}`
        },
        lib: {
          'crate-type': ['staticlib']
        },
        dependencies: {}
      };
      for (const crate of ctx.temporalCrates) {
        const name = crate.split('@', 1)[0];
        if (name === 'temporal_capi' || typeof sourceManifest.dependencies[name] === 'object') {
          manifest.dependencies[name] = sourceManifest.dependencies[name];
        }
      }

      const cargoTOML = header + TOML.stringify(manifest);
      await fs.writeFile(path.join(ctx.nodeDir, nodeCratesDir, 'Cargo.toml'), cargoTOML);
    },
  };
}

// Note that the crates vendored in third_party/rust/chromium_crates_io already have any custom
// Chromium patches applied by gnrt, so we don't need to worry about patching them ourselves.
function vendorCrates() {
  return {
    title: 'Copy vendored crates',
    task: async(ctx, task) => {
      const chromiumVendor = path.join(ctx.nodeDir, chromiumCratesDir, 'vendor');
      const nodeVendor = path.join(ctx.nodeDir, nodeCratesDir, 'vendor');
      await fs.mkdir(nodeVendor);

      const subtasks = [];
      for (const dir of await fs.readdir(chromiumVendor)) {
        const crate = await getCrateInfo(dir);
        if (!crate || !ctx.temporalCrates.has(`${crate.name}@${crate.version}`)) continue;
        if (crate.name === 'temporal_capi') {
          ctx.temporalCAPIDirectory = dir;
        }
        subtasks.push({
          title: dir,
          task: async(ctx) => {
            await fs.cp(
              path.join(chromiumVendor, dir),
              path.join(nodeVendor, dir),
              { recursive: true }
            );
          }
        });
      }

      return task.newListr(subtasks, { concurrent: ctx.concurrent });

      async function getCrateInfo(crate) {
        try {
          const manifest = TOML.parse(
            await fs.readFile(path.join(chromiumVendor, crate, 'Cargo.toml'), 'utf8')
          );
          return manifest.package;
        } catch {
          return null;
        }
      }
    }
  };
}

function generateLockfile() {
  return {
    title: 'Generate lockfile',
    task: (ctx) => forceRunAsync(ctx.cargo, ['generate-lockfile', '--quiet', '--offline'], {
      ignoreFailure: false,
      spawnArgs: { cwd: path.join(ctx.nodeDir, nodeCratesDir) }
    })
  };
}

function updateGYP() {
  return {
    title: 'Update include path in crates.gyp',
    task: async(ctx, task) => {
      const filePath = path.join(ctx.nodeDir, nodeCratesDir, 'crates.gyp');
      let gyp = await fs.readFile(filePath, 'utf8');
      const [definition, currentDirectory] = gyp.match(/'temporal_capi_dir': '(.+?)'/);
      if (currentDirectory === ctx.temporalCAPIDirectory) {
        task.skip('crates.gyp already up-to-date');
        return;
      }
      gyp = gyp.replace(definition, `'temporal_capi_dir': '${ctx.temporalCAPIDirectory}'`);
      await fs.writeFile(filePath, gyp);
    }
  };
}

function commitChanges() {
  return {
    title: 'Commit changes',
    task: async(ctx) => {
      await ctx.execGitNode('add', ['--force', 'deps/crates']);
      await ctx.execGitNode(
        'commit',
        ['-m', `deps: update Rust crates for V8 ${ctx.newVersion}`]
      );
    }
  };
}
